/*
 * Copyright (C) 2025 Lia Garcia Pérez
 *
 * This file is part of paparazzi.
 *
 * paparazzi is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * paparazzi is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with paparazzi; see the file COPYING.  If not, write to
 * the Free Software Foundation, 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 */

#include <math.h>
#include "std.h"

#include "gvf.h"
#include "gvf_low_level_control.h"
#include "autopilot.h"
#include "../gvf_common.h"
#include "modules/multi/traffic_info.h"
#include "modules/datalink/telemetry.h"

// CBF parameters
cbf_parameters cbf_param;

// Robots state

cbf_state_t cbf_ac_state = {0};
cbf_tab_entrie_t cbf_obs_tables[CBF_MAX_NEIGHBORS];
// State
gvf_st gvf_state;
gvf_common_field gvf_c_field;

// Time variables to check if GVF is active
uint32_t gvf_t0 = 0;



#if PERIODIC_TELEMETRY


//TODO Create the message

static void send_cbf(struct transport_tx *trans, struct link_device *dev)
{
  uint16_t n = 1;
  if (cbf_control.n_neighborns > 0) { // n = 0 doesn't make sense
    n = cbf_control.n_neighborns;
  }
  
  for (int i = 0; i < n; i++) {
    cbf_telemetry.acs_available[i] = cbf_obs_tables[i].available;
  }

  pprz_msg_send_CBF(trans, dev, AC_ID, &cbf_ac_state.xi_x,&cbf_ac_state.xi_y,
  				&cbf_ac_state.xicbf_x,&cbf_ac_state.xicbf_y,
  				&cbf_ac_state.nei,&cbf_ac_state.active_conds,
  				&cbf_ac_state.r,&cbf_ac_state.alpha);
}
#endif // PERIODIC TELEMETRY
 


void gvf_cbf_init(void)
{

  cbf_param.r = 2;
  cbf_param.alpha = 1;
  
#if PERIODIC_TELEMETRY
  register_periodic_telemetry(DefaultPeriodic, PPRZ_MSG_ID_CBF, send_cbf);
#endif
}

//TODO Create the functions to fill in the table and to send the status to other robots

void cbf_init(void) 
{ 
  // Initilize the obstacles tables with the ac_id of the neighborns
  uint16_t cbf_nei_ac_ids[CBF_MAX_NEIGHBORS] = CBF_NEI_AC_IDS;
  for (int i = 0; i < CBF_MAX_NEIGHBORS; i++) {
    if (cbf_nei_ac_ids[i] > 0 && cbf_nei_ac_ids[i] < 255) {
      cbf_obs_tables[i].ac_id = cbf_nei_ac_ids[i];
      cbf_telemetry.acs_id[cbf_control.n_neighborns] = cbf_nei_ac_ids[i]; // for telemetry

      cbf_control.n_neighborns = cbf_control.n_neighborns + 1;
    } else {
      cbf_obs_tables[i].ac_id = 0;
    }
    cbf_obs_tables[i].available = 0;
    cbf_telemetry.acs_timeslost[i] = 0; // for telemetry
  }

  #if PERIODIC_TELEMETRY
  register_periodic_telemetry(DefaultPeriodic, PPRZ_MSG_ID_CBF, send_cbf);
  #endif // PERIODIC_TELEMETRY
}
// GVF modified by the CBFs generated by other agents
void gvf_cbf(){

float eta[CBF_MAX_NEIGHBORS];
float Aa[CBF_MAX_NEIGHBORS][2];
int j=0;
 for (uint8_t i = 0; i < CBF_MAX_NEIGHBORS; ++i)  {

    if (cbf_obs_tables[i].available == 0) { continue; } // ignore unavailable neighborns

    uint32_t timeout = now - cbf_obs_tables[i].t_last_msg;

    if (timeout > cbf_params.timeout) { // ignore died neighborns 
      cbf_obs_tables[i].available = 0;
      cbf_telemetry.acs_timeslost[i] = cbf_telemetry.acs_timeslost[i] + 1;
      cbf_obs_tables[i].omega_safe = 0;
      continue;
      } 
     // Build the eta[j] (safe function)
     float dx=cbf_ac_state.x-cbf_obs_tables[i].x
     float dy=cbf_ac_state.y-cbf_obs_tables[i].y
     eta[i]=(dx)**2+(dy)**2-cbf_param-r**2;
     //  Test the condition for each neighbour. If the condition does not hold the requierement is active
     float b=0.25*cbf_param.alpha*eta[i]**3;
     if ((-dx*gvf_c_field.xi_x-dy*gvf_c_field.xi_y) > b){ // Condition is active
     	Aa[j][0]=-dx;
     	Aa[j][1]=-dy;
     	b[j]=b;
     	j++;
     }
     }
  int active_conds=j
  // Lagrange multiplier
  float Aact[active_conds][active_conds];
  for (uint8_t i=0;i<active_conds;i++){
  	for   (uint8_t j=0;j<active_conds;j++){
  		Aact[i][j]=Aa[i][0]*A[j][0]+A[i][1]*A[j][1]
  	}
  }
  float L[active_conds][active_conds],D[active_conds],invA[active_conds][active_conds];
  ldltDecomposition(Aact,L, D);
  inverseUsingLDLT(L,D, invA);
  float lambda_A[active_conds];
  for (uint8_t i=0;i<active_conds;i++){
  	su=0;
  	for   (uint8_t j=0;j<active_conds;j++){
  		su=invA[i][j]*(A[j][0]*gvf_c_field.xi_x+A[j][1]*gvf_c_field.xi_y-b[j]);
  	}
  	lambda_A[i]=su
  }  
  float cx=0,xy=0;
  for (uint8_t i=0;i<active_conds;i++){
  	cx=cx+A[i][0]*lambda[i];
  	cy=cy+A[i][1]*lambda[i];
  
  }   
  
  // Modified field (only if there are active conditions
  if (active_conds>0){
  	gvf_c_field.xi_x=gvf_c_field.xi_x-cx;
  	gvf_c_field.xi_y=gvf_c_field.xi_x-cy;
  }
  
     
}
// Helpers

#define N CBF_MAX_NEIGHBORS

void ldltDecomposition(double A[N][N], double L[N][N], double D[N]) {
    for (int i = 0; i < N; i++) {
        for (int j = 0; j <= i; j++) {
            double sum = 0;

            if (j == i) {
                for (int k = 0; k < j; k++) {
                    sum += L[j][k] * L[j][k] * D[k];
                }
                D[j] = A[j][j] - sum;
                L[j][j] = 1.0;
            } else {
                for (int k = 0; k < j; k++) {
                    sum += L[i][k] * L[j][k] * D[k];
                }
                L[i][j] = (A[i][j] - sum) / D[j];
            }
        }
    }
}

void forwardSubstitution(double L[N][N], double b[N], double y[N]) {
    for (int i = 0; i < N; i++) {
        double sum = 0.0;
        for (int j = 0; j < i; j++) {
            sum += L[i][j] * y[j];
        }
        y[i] = b[i] - sum;
    }
}

void diagonalSolve(double D[N], double y[N], double z[N]) {
    for (int i = 0; i < N; i++) {
        z[i] = y[i] / D[i];
    }
}

void backwardSubstitution(double L[N][N], double z[N], double x[N]) {
    for (int i = N - 1; i >= 0; i--) {
        double sum = 0.0;
        for (int j = i + 1; j < N; j++) {
            sum += L[j][i] * x[j];
        }
        x[i] = z[i] - sum;
    }
}

void inverseUsingLDLT(double L[N][N], double D[N], double invA[N][N]) {
    double y[N], z[N], x[N], e[N];

    for (int i = 0; i < N; i++) {
        for (int j = 0; j < N; j++) {
            e[j] = (i == j) ? 1.0 : 0.0; // Vector unitario
        }

        forwardSubstitution(L, e, y);
        diagonalSolve(D, y, z);
        backwardSubstitution(L, z, x);

        for (int j = 0; j < N; j++) {
            invA[j][i] = x[j];
        }
    }
}
